### ISSUE TITLE
Add optional input for the text body of the mail

### ISSUE THREAD

**Issue by YourPsychiatrist** [simonschiller/tutorbot#4]
Let the user either supply a plain text file or ad-hoc input as mail body.

**Comment by simonschiller** [comment]
I'd prefer to keep all the input in the command line. How would you handle line breaks? I was thinking of adding a special char sequence (`<br/>` maybe) to signal line breaks.

**Comment by YourPsychiatrist** [comment]
maybe the usual \n? :thinking: Lets go with the <br/> for now.
